dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
install: pip install tox-travis coveralls
script:
    - tox
after_success:
    - coveralls
matrix:
  allow_failures:
    - python: "nightly"
